teleop_twist_joy_node:
  ros__parameters:
    use_sim_time: False
    axis_linear.x: 1
    scale_linear.x: 0.2
    scale_linear_turbo.x: 1.0
    axis_angular.yaw: 0
    scale_angular.yaw: 1.0
    scale_angular_turbo.yaw: 1.0
    enable_button: 4
    enable_turbo_button: 5

joy_node:
  ros__parameters:
    use_sim_time: False
    deadzone: 0.1
    autorepeat_rate: 20.0
    dev: /dev/input/js0
